### ISSUE TITLE
Type error on GenshinJailbreakBypass.plist

### ISSUE THREAD

**Issue by Gravitationyw** [iVoider/GenshinJailbreakBypass#1]
1 type error on GenshinJailbreakBypass.plist
{ Filter = { Bundles = ( "com.miHoYo.GenshinImpact", "com.miHoYo.Yanshen" ); }; }
should be
{ Filter = { Bundles = ( "com.miHoYo.GenshinImpact", "com.miHoYo.Yuanshen" ); }; }

I don't know wheather it cause this tweak doesn't work for CN server. If not, would you please help to rewrite tweak for compatible with CN server? Thank you very much!

**Comment by yueqingyou** [comment]
Hi, I have made it.
details:
[https://vccv.cc/2021/12/23/ios-jailbreak-genshin/](https://vccv.cc/2021/12/23/ios-jailbreak-genshin/)
Thanks to author again.

**Comment by iVoider** [comment]
Thanks, problem was fixed.
