### ISSUE TITLE
Permission to host the package

### ISSUE THREAD

**Issue by beer-psi** [iVoider/GenshinJailbreakBypass#3]
Hi, I'm a co-maintainer of https://bypass.beerpsi.me, a website documenting bypass + app pairs, and tries to make it simple for people to bypass jailbreak detection. We also host a repo at https://bypass.beerpsi.me/repo which contains a few app-specific bypasses. Would you mind if I host GenshinJailbreakBypass on said repo to make the package more accessible?

**Comment by iVoider** [comment]
Feel free to post

**Comment by beer-psi** [comment]
Thanks!
